CREATE DATABASE infinity_car;
USE infinity_car;

CREATE TABLE brands (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL, 
brand VARCHAR(100) NOT NULL
);

CREATE TABLE categories (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL, 
type_auto VARCHAR(100) NOT NULL
);

CREATE TABLE colors (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
color VARCHAR(100) NOT NULL
);

CREATE TABLE exchangerate (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
tc float
);
CREATE TABLE inflation (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
inflation float
);
CREATE TABLE promotions (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
promotions float
);

CREATE TABLE km_intervals (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
intervals DECIMAL(10,0) NOT NULL
);



CREATE TABLE roles (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
category VARCHAR(100)
);

CREATE TABLE users (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
full_name VARCHAR(100) NOT NULL,
user VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
date_birth DATE NOT NULL, 
email VARCHAR(100) NOT NULL,
phone VARCHAR(100) NOT NULL,
roll_id INT UNSIGNED NOT NULL,
image TEXT NOT NULL, 
state INT NOT NULL,
FOREIGN KEY (roll_id) REFERENCES roles (id)
);

CREATE TABLE years (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
year INT(100) NOT NULL
);
CREATE TABLE models (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
model VARCHAR(100),
brand_id INT UNSIGNED NOT NULL,
year_id INT UNSIGNED NOT NULL,
categories_id INT UNSIGNED NOT NULL,
FOREIGN KEY (brand_id) REFERENCES brands (id),
FOREIGN KEY (year_id) REFERENCES years (id),
FOREIGN KEY (categories_id) REFERENCES categories (id)
);

CREATE TABLE products (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
name VARCHAR(100) NOT NULL,
brand_id INT UNSIGNED NOT NULL,
color_id INT UNSIGNED NOT NULL,
model_id INT UNSIGNED NOT NULL,
year_id INT UNSIGNED NOT NULL,
km_id INT UNSIGNED NOT NULL,
prices BIGINT,
categories_id INT UNSIGNED NOT NULL,
image_filename VARCHAR(100),
image_filename2 VARCHAR(100),
image_filename3 VARCHAR(100),
image_filename4 VARCHAR(100),
image_filename5 VARCHAR(100),
transmission VARCHAR(100),
conditions VARCHAR(100),
type_fuel VARCHAR(100),
discount VARCHAR(100),
descripcion VARCHAR(300) NULL,
views int ,
stock VARCHAR(100),
exchange_id  INT UNSIGNED NOT NULL,
inflation_id  INT UNSIGNED NOT NULL,
promos_id INT UNSIGNED NOT NULL,
FOREIGN KEY (brand_id) REFERENCES brands (id),
FOREIGN KEY (color_id) REFERENCES colors (id),
FOREIGN KEY (model_id) REFERENCES models (id),
FOREIGN KEY (year_id) REFERENCES years (id),
FOREIGN KEY (km_id) REFERENCES km_intervals (id),
FOREIGN KEY (categories_id) REFERENCES categories (id),
FOREIGN KEY (exchange_id) REFERENCES exchangerate (id),
FOREIGN KEY (inflation_id) REFERENCES inflation (id),
FOREIGN KEY (promos_id) REFERENCES promotions (id)

);